image: macos-monterey

skip_branch_with_pr: true

skip_commits:
  files:
    - docs/**/*
    - media/**/*
    - "*.md"

environment:
    PYTHON_STACK: python 3.10
    FLUTTER_MACOS_URL: https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.13.7-stable.zip
    GITHUB_TOKEN:
      secure: J8cyNmJ9GAu0Z+1YM1fqHeP/nWG36aV690f8peUvadrUrEtCWvOsK8xIubGD7hEI

    matrix:
    - job_name: Build Python for iOS
      job_group: build_python_darwin
      APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey

    - job_name: Build Python for Android
      job_group: build_python_android
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
    
    - job_name: Build Python for Windows
      job_group: build_python_windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    - job_name: Build Python for Macos
      job_group: build_python_macos
      APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey
    
    - job_name: Build Python for Linux
      job_group: build_python_linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004




test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: false



for:
  # ======================================
  #      Build Python for iOS
  # ======================================

  - matrix:
      only:
        - job_name: Build Python for iOS

    install:
      - pip3 install flet
      - pip3 install flet-route
      - pip3 install openpyxl
      - export PATH=$PATH:$(python3 -m site --user-base)/bin

      # install Kivy toolchain
      - pip3 list
      - pip3 install git+https://github.com/flet-dev/python-for-ios.git
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install autoconf automake libtool pkg-config
      - brew link libtool
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install cocoapods
      - curl $FLUTTER_MACOS_URL -o "$HOME/flutter_macos_stable.zip"
      - unzip -qq "$HOME/flutter_macos_stable.zip" -d $HOME
      - export PATH="$PATH:$HOME/flutter/bin"
      - flutter channel stable
      - flutter upgrade
      - flutter config --enable-macos-desktop
      - flutter doctor

    build_script:
      # build Python 3
      - flet build ipa --template .
    
    after_build:
      - echo "Verificando la existencia de archivos .ipa en ./build/ipa"
      #- toolchain build python3
      - ls dist
      - ls ./build/ipa
      - echo "Creando archivo zip con app.tar.gz"
      - zip -r fletsheet-ios.zip ./build/ipa/Runner.xcarchive


    artifacts:
      - path: fletsheet-ios.zip

    

  # ======================================
  #      Build Python for Android
  # ======================================

  - matrix:
      only:
        - job_name: Build Python for Android

    install:
      # update build version
      - pip3 install flet
      - pip3 install flet-route
      - pip3 install openpyxl
      - pip3 install p4a-build
      - pip3 install --upgrade cython
      - export PATH=$PATH:$(python3 -m site --user-base)/bin

      # install NDK
      - export ANDROID_SDK_ROOT="/usr/lib/android-sdk"
      - export NDK_VERSION=25.2.9519653
      - export SDK_VERSION=android-33
      - echo "y" | sdkmanager --install "ndk;$NDK_VERSION" --channel=3 > /dev/null
      - echo "y" | sdkmanager --install "platforms;$SDK_VERSION" > /dev/null

      # install Kivy for Android
      - pip3 install git+https://github.com/flet-dev/python-for-android.git@3.11.6
      - p4a --help
      - p4a create --requirements python3 --arch arm64-v8a --arch armeabi-v7a --arch x86_64 --sdk-dir $ANDROID_SDK_ROOT --ndk-dir $ANDROID_SDK_ROOT/ndk/$NDK_VERSION --dist-name serious_python
      - flutter upgrade --force

    build_script:
      - flet build apk --template .

    after_build:
      - echo "Verificando la existencia de archivos .apk en ./build/apk"
      - ls ./build/apk
      - zip -r fletsheet-android.zip ./build/apk/*.apk

    artifacts:
      - path: fletsheet-android.zip

      
    

#
# Windows package
#


  - matrix:
      only:
        - job_name: Build Python for Windows

    install:
    - "pip install flet"
    - "pip install flet-route"
    - "pip install pyinstaller"
    - "pip install openpyxl"
    
    build_script:
      - flet pack main.py --name fletsheet --icon icon.ico --product-name fletsheet --product-version "0.0.1" --copyright "MIT" --add-data "assets;assets"
    after_build:
      - 7z a fletsheet-windows.zip %CD%\dist\*.exe
    artifacts:
      - path: fletsheet-windows.zip
      

 

#
# macOS package
#

  - matrix:
      only:
        - job_name: Build Python for Macos


    install:
      - pip3 install flet
      - pip3 install flet-route
      - pip3 install openpyxl
      - export PATH=$PATH:$(python3 -m site --user-base)/bin
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install cocoapods
      - curl $FLUTTER_MACOS_URL -o "$HOME/flutter_macos_stable.zip"
      - unzip -qq "$HOME/flutter_macos_stable.zip" -d $HOME
      - export PATH="$PATH:$HOME/flutter/bin"
      - flutter channel stable
      - flutter upgrade
      - flutter config --enable-macos-desktop
      - flutter doctor

    build_script:
      - flet build macos --template .

    
    after_build:
    - echo "Verificando la existencia de archivos .app en ./build/macos"
    - ls ./build/macos
    - zip -r fletsheet-macos.zip ./build/macos/*.app

    artifacts:
      - path: fletsheet-macos.zip

  



#
# Linux package
#

  - matrix:
      only:
        - job_name: Build Python for Linux

    install:
      -  sudo pip3 install flet
      -  sudo pip3 install flet-route
      -  sudo pip3 install openpyxl
      -  export PATH=$PATH:$(python3 -m site --user-base)/bin
      #-  sudo apt update --allow-releaseinfo-change
      -  sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
      -  flutter upgrade --force

    build_script:
      - sudo flet build linux --template .

    after_build:
      - tar -czvf fletsheet-linux.tar.gz ./dist/*
    artifacts:
      - path: fletsheet-linux.tar.gz


  


 