name: CI for Android, macOS, iOS, web, windows, linux

on: 
  #push:
  #  branches: 
  #    - main
  release:
    types: [published]

permissions:
  contents: write

jobs:

  
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Python and Flet
      run: |
        pip3 install flet

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        

    - name: Build macosapp
      run: flet build macos -vv
    
    - name: Archive macosapp
      run: |
        zip -r quitadondo-macos.zip ./build/macos/*.app

    - name: Upload macosapp to GitHub Release
      run: |
        gh release upload ${{ github.event.release.tag_name }} quitadondo-macos.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  



  build-android:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin' # Eclipse Adoptium

    - name: Install Android Command Line Tools
      run: |
        brew install --cask android-commandlinetools


    - name: Accept Licenses
      run: yes | sdkmanager --licenses

    - name: Install Android SDK and Tools
      run: |
        sdkmanager "cmdline-tools;latest" "platforms;android-33" "emulator" "tools" "platform-tools" "ndk;25.2.9519653"

    - name: Install Python and Flet
      run: |
        pip3 install flet
        pip3 install git+https://github.com/flet-dev/python-for-android.git@3.11.6
        pip3 install --upgrade cython
    
    - name: Set up p4a
      run: |
        export ANDROID_SDK_ROOT="/Users/runner/Library/Android/sdk"
        export NDK_VERSION=25.2.9519653
        export SDK_VERSION=android-33
        ( echo "Y"; while true; do echo "N"; done ) | p4a create --requirements python3 --arch arm64-v8a --arch armeabi-v7a --arch x86_64 --sdk-dir $ANDROID_SDK_ROOT --ndk-dir $ANDROID_SDK_ROOT/ndk/$NDK_VERSION --dist-name mydist
        export SERIOUS_PYTHON_P4A_DIST=$HOME/.python-for-android/dists/mydist
       

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        

    - name: Build APK
      run: flet build apk -vv

    - name: Archive APK
      run: |
        zip -r quitadondo-android.zip ./build/apk/*.apk

      
    - name: Upload APK to GitHub Release
      run: |
        gh release upload ${{ github.event.release.tag_name }} quitadondo-android.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
 
  
  build-web:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.6
    
    - name: use the environmet
      run: |

        pip install flet
        flet build web -vv
    
    
    - name: Archive webapp
      run: zip -r quitadondo-web.zip ./build/web/
        
    - name: Upload APK to GitHub Release
      run: gh release upload ${{ github.event.release.tag_name }} quitadondo-web.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-web-hash:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.6
    
    - name: use the environmet
      run: |

        pip install flet
        flet build web --route-url-strategy hash
    
    
    - name: Archive webapp
      run: zip -r quitadondo-web-hash.zip ./build/web/
        
    - name: Upload APK to GitHub Release
      run: gh release upload ${{ github.event.release.tag_name }} quitadondo-web.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'


    - name: Install Flet
      run: pip install flet
        

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Build windows app
      run: flet build windows -vv

    - name: Archive windows app
      run: |
        7z a quitadondo-windows.zip .\build\windows\*


    - name: Upload windows app to GitHub Release
      run: |
        gh release upload ${{ github.event.release.tag_name }} quitadondo-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    
    - name: install dependences 
      run: |
        sudo apt update --allow-releaseinfo-change
        sudo apt install ninja-build
        sudo apt install -y xvfb libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.6
    
    - name: use the environmet
      id: build-linux
      continue-on-error: true
      run: |
        pip install flet
        flet build linux -vv 


    - name: Archive linux app
      run: |
        zip -r quitadondo-linux.zip ./build/linux/*

    
    - name: Upload linux app to GitHub Release
      run: |
        gh release upload ${{ github.event.release.tag_name }} quitadondo-linux.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
  build-ios:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
            
    - name: Set up Python 3.11.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.8
    
    - name: use the environmet
      run: |
        /Users/runner/hostedtoolcache/Python/3.11.8/x64/bin/python3 -m venv .venv
        source .venv/bin/activate
        pip install flet
        pip install git+https://github.com/flet-dev/python-for-ios.git
        brew install autoconf automake libtool pkg-config
        brew link libtool
        toolchain build python3 
        export SERIOUS_PYTHON_IOS_DIST='/Users/runner/work/quitadondo/quitadondo/dist'
        flet build ipa -vv

    
    - name: Upload IPA to GitHub Release
      run: |
        gh release upload ${{ github.event.release.tag_name }} quitadondo--ios.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
  